# General Settings
title = "JSCFS - John Snow Charity Fashion Show"
baseURL = "https://jscfs.co.uk" #YOUR SITE URL
languageCode = "en-gb"
theme = "aster"
resourceDir = "resources"
paginate = 4
summaryLength = 20
DefaultContentLanguage = "en"

# Menu Settings
[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2
[[menu.main]]
  identifier = "years"
  name = "Years"
  url = "/years/"
  weight = 3
  [[menu.main]]
    identifier = "2024"
    parent = "years"
    name = "2024"
    url = "/2024/"
    weight = 1
  [[menu.main]]
    identifier = "2023"
    parent = "years"
    name = "2023"
    url = "/2023/"
    weight = 1
  [[menu.main]]
    identifier = "2022"
    parent = "years"
    name = "2022"
    url = "/2022/"
    weight = 1
  [[menu.main]]
    identifier = "2021"
    parent = "years"
    name = "2021"
    url = "/2021/"
    weight = 1
  [[menu.main]]
    identifier = "2020"
    parent = "years"
    name = "2020"
    url = "/2020/"
    weight = 1
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 5
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 6

# Main Settings
[params]
dateFormat = "January 1, 2024"
authorName = "Max Roulstone"
disqusComments = "test" #YOUR DISQUS COMMENTS SHORTNAME
formspreeURL = "https://formspree.io/f/mbjnydae" #YOUR FORMSPREE URL
googleAnalytics = "G-PXT13QSZRN" #YOUR GOOGLE ANALYTICS CODE

# Preloader Settings
[params.preloader]
logo = "images/text_logo_white.png"

# Header Settings
[params.header]
logo = "images/text_logo_white.png"

# Footer Settings
[params.footer]
copyright = "Copyright © 2024 Roulstone"
col1_title = "Address:"
col1_text = "John Snow College,<br/>Durham, UK"
col2_title = "Follow Us:"
col2_text = ""
col3_title = "Get in touch:"
col3_text = "johnsnowfashionshow@gmail.com"

# Social Settings
[[params.social]]
title = "Instagram"
icon = "fab fa-instagram"
url = "https://instagram.com/jscfs/"
weight = 1
[[params.social]]
title = "Facebook"
icon = "fab fa-facebook"
url = "https://facebook.com/johnsnowcfs/"
weight = 1
[[params.social]]
title = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://linkedin.com/company/jscfs/"
weight = 2


# Sidebar
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ]
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]

# Portfolio Settings
[params.portfolio]
homeNumOfItems = 12
[[params.portfolio.filters]]
name = "UI UX Design"
slug = "ui-ux-design"
[[params.portfolio.filters]]
name = "Photography"
slug = "photography"
[[params.portfolio.filters]]
name = "Development"
slug = "development"
[[params.portfolio.filters]]
name = "Branding"
slug = "branding"

# Sitemap Settings
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
