# General Settings
title = "JSCFS | John Snow Charity Fashion Show"
baseURL = "https://jscfs.co.uk" #YOUR SITE URL
languageCode = "en-gb"
theme = "aster"
resourceDir = "resources"
paginate = 4
summaryLength = 20
DefaultContentLanguage = "en"
Description = "An annual event led entirely by students of John Snow College - Durham University aiming to raise money for local charites in the North East of England."
enableRobotsTXT = true

# Menu Settings
[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2
[[menu.main]]
  identifier = "donate"
  name = "Donate"
  url = "https://www.justgiving.com/page/jscfs2024"
  weight = 3
[[menu.main]]
  identifier = "years"
  name = "Years"
  url = "/portfolio/"
  weight = 3

# Main Settings
[params]
dateFormat = "January 1, 2024"
authorName = "Max Roulstone"
disqusComments = "test" #YOUR DISQUS COMMENTS SHORTNAME
formspreeURL = "https://formspree.io/f/mbjnydae" #YOUR FORMSPREE URL
googleAnalytics = "G-PXT13QSZRN" #YOUR GOOGLE ANALYTICS CODE

# Preloader Settings
[params.preloader]
logo = "images/text_logo_white.png"

# Header Settings
[params.header]
logo = "images/text_logo_white.png"

# Footer Settings
[params.footer]
copyright = "Copyright © 2024 Max Roulstone"
col1_title = "Address:"
col1_text = "John Snow College,<br/>Durham, UK"
col2_title = "Follow Us:"
col2_text = ""
col3_title = "Get in touch:"
col3_text = "johnsnowfashionshow@gmail.com"

# Social Settings
[[params.social]]
title = "Instagram"
icon = "fab fa-instagram"
url = "https://instagram.com/jscfs/"
weight = 1
[[params.social]]
title = "Facebook"
icon = "fab fa-facebook"
url = "https://facebook.com/johnsnowcfs/"
weight = 1
[[params.social]]
title = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://linkedin.com/company/jscfs/"
weight = 2
[[params.social]]
title = "JustGiving"
icon = "fas fa-donate"
url = "https://www.justgiving.com/page/jscfs2024"
weight = 2


# Sidebar
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ]
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]

# Portfolio Settings
[params.portfolio]
homeNumOfItems = 12
[[params.portfolio.filters]]
name = "2024"
slug = "2024"
[[params.portfolio.filters]]
name = "2023"
slug = "2023"
[[params.portfolio.filters]]
name = "2022"
slug = "2022"
[[params.portfolio.filters]]
name = "2021"
slug = "2021"
[[params.portfolio.filters]]
name = "2020"
slug = "2020"

[params.models]
homeNumOfItems = 12
[[params.models.filters]]
name = "Info"
slug = "info"
[[params.models.filters]]
name = "Rehearsals"
slug = "rehearsals"

# Sitemap Settings
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


